package com.expensemanagement.AI;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;

import java.util.Map;

/**
 * Unified response DTO for all voice command endpoints.
 * Returned by VoiceCommandController.
 *
 * JSON fields:
 * intent, params, reply, message (alias for reply), data, fallback,
 * processingMs
 */
@Data
@Builder
public class VoiceResponse {

    /** The detected intent label (e.g. "SEARCH_EXPENSES", "APPROVE_EXPENSE") */
    private String intent;

    /** Raw params extracted by the AI (e.g. { "status": "PENDING" }) */
    private Map<String, Object> params;

    /**
     * Human-readable, spoken-word reply generated by AI assistant.
     * Shown in the VoiceResultPanel and optionally TTS'd by the browser.
     * Also exposed as {@code message} for API spec compatibility.
     */
    private String reply;

    /**
     * Alias for {@link #reply} — returned as {@code message} in JSON.
     * Matches the spec: { "intent": "APPROVE_EXPENSE", "message": "..." }
     */
    @JsonProperty("message")
    public String getMessage() {
        return reply;
    }

    /**
     * Structured result data for the frontend to render.
     * E.g. a list of expenses, budget stats, etc.
     */
    private Object data;

    /** True when Ollama was unreachable and a safe default was returned. */
    private boolean fallback;

    /** End-to-end processing time in milliseconds. */
    private long processingMs;

    /**
     * Response status — matches the API spec.
     * Values: SUCCESS | UNAUTHORIZED | ERROR | UNKNOWN
     */
    private String status;

    // ── Factories ─────────────────────────────────────────────────────────────

    public static VoiceResponse success(String intent, Map<String, Object> params,
            String reply, Object data, long ms) {
        return VoiceResponse.builder()
                .intent(intent)
                .params(params)
                .reply(reply)
                .data(data)
                .status("SUCCESS")
                .fallback(false)
                .processingMs(ms)
                .build();
    }

    /** Convenience factory used by VoiceActionService for UNAUTHORIZED results. */
    public static VoiceResponse unauthorized(String intent, long ms) {
        return VoiceResponse.builder()
                .intent(intent)
                .params(Map.of())
                .reply("You are not allowed to perform this action.")
                .data(null)
                .status("UNAUTHORIZED")
                .fallback(false)
                .processingMs(ms)
                .build();
    }

    public static VoiceResponse fallback(long ms) {
        return VoiceResponse.builder()
                .intent("UNKNOWN")
                .params(Map.of())
                .reply("I'm having trouble understanding right now. Please try again, or use the search filters below.")
                .data(null)
                .status("UNKNOWN")
                .fallback(true)
                .processingMs(ms)
                .build();
    }

    public static VoiceResponse offline(long ms) {
        return VoiceResponse.builder()
                .intent("UNKNOWN")
                .params(Map.of())
                .reply("The AI assistant is temporarily offline. Your voice command could not be processed. Please use the manual search filters.")
                .data(null)
                .status("ERROR")
                .fallback(true)
                .processingMs(ms)
                .build();
    }
}
